import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/ThemeProvider';
import ThemeToggle from '@/components/ThemeToggle';
import Link from 'next/link';
import AgencySelectSSRWrapper from '@/components/AgencySelectSSRWrapper';
import AgencyContextProvider from '@/context/AgencyContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Bus Live',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <AgencyContextProvider>
              <header className="border-b-4 flex justify-between px-2 md:px-6 py-2 md:py-4 items-center">
                <Link href="/">
                  <h1 className="font-bold text-lg">Bus Live</h1>
                </Link>

                <AgencySelectSSRWrapper />
                <ThemeToggle />
              </header>
              {children}
            </AgencyContextProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
